groups:
  - name: node_alerts
    rules:
      - alert: HighCPU
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 70
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU on {{ $labels.instance }}"
          
      - alert: HighRAM
        expr: 100 - (avg by(instance) (rate(node_ram_seconds_total{mode="idle"}[5m])) * 100) > 70
        for: 5m
        labels:
          severity: warning
        annotations:
          summart: "High RAM on {{ $labels.instance }}"

      - alert: ContainerDown
        expr: time() - container_last_seen{name=~"radarr|sonarr|prowlarr|bazarr|qbittorrent"} > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.name }} is down"

      - alert: MonitoringDown
        expr: time() - container_last_seen{name=~"cadvisor|node-exporter|alertmanager|grafana"} > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.name }} is down"