templates:
  - '/config/email.tmpl'

route:
  receiver: 'mail'
  repeat_interval: 12h
  group_by: [ alertname ]

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'serveralertsacc@gmail.com'
        auth_password_file: '/run/secrets/smtp_password'
        from: 'serveralertsacc@gmail.com'
        to: 'eskilwelin@gmail.com'
        html: '{{ template "email.custom.html" . }}'
        headers:
          Subject: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'