x-healthcheck: &healtcheck
  start_period: 15s
  interval: 30s
  timeout: 5s
  retries: 3

services:
  fileserver:
    build:
      context: .
      secrets:
        - samba_secrets
    container_name: fileserver
    ports: 
      - "445:445"
    volumes: 
      - ./share_data:/share
    restart: unless-stopped
    networks:
      - backend

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file: mariadb.env
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      <<: *healthcheck
    restart: unless-stopped
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: phpmyadmin.env
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - frontend
      - backend
    
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    depends_on:
      phpmyadmin:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -kf https://localhost/ || exit 1"]
      <<: *healthcheck    
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./key.pem:/etc/nginx/ssl/key.pem:ro
      - ./cert.pem:/etc/nginx/ssl/cert.pem:ro
    restart: unless-stopped
    networks:
      - frontend

volumes:
  mariadb_data:

networks:
  frontend:
  backend:

secrets:
  samba_secrets: 
    file: samba_secrets.txt