[global]
    security = user
    map to guest = never

#   turn off print stuff
    printing = bsd
    printcap name = /dev/null
    load printers = no
    disable spoolss = yes

#   default deadtime to disconnect after N minutes of inactivity is 10080
    deadtime = 5

[DB_Backup]
    path = /share
    browsable = yes
    read only = no
    valid users = backupuser, eskil